### PR TITLE
fix(processor): log 400 responses, harden allowed-roots cache, functional symlink test (TYPO3_12 backport for #70)

### LINKED ISSUE #70: Bug: image variants return HTTP 400
## Description

All newly requested image variants return HTTP 400 on environments where `fileadmin` is a symlink to an external path (e.g. EFS/NFS mount).

## Analysis

The `isPathWithinPublicRoot()` method introduced in 1.1.0 uses `realpath()` to resolve the image path before comparing it against the TYPO3 public root. `realpath()` follows symlinks — if `fileadmin` is a symlink pointing outside the public root, the resolved path no longer starts with the expected prefix and the check returns `false` → 400.

**Example:**
- TYPO3 public path: `/var/www/public`
- `/var/www/public/fileadmin` → symlink → `/mnt/efs/cms/fileadmin`
- `realpath('/var/www/public/fileadmin/_processed_/6/d/foo.jpg')` returns `/mnt/efs/cms/fileadmin/_processed_/6/d/foo.jpg`
- `str_starts_with('/mnt/efs/...', '/var/www/public/')` → **false** → 400

Already-cached variants (where `pathVariant` exists on disk inside `public/processed/`) are not affected — only uncached variants trigger the path walk that hits the symlink.

## Reproduction

```bash
# Replace fileadmin with a symlink pointing outside public/
rm -rf public/fileadmin
ln -s /tmp/fileadmin_extern public/fileadmin
mkdir -p /tmp/fileadmin_extern/_processed_/6/d/
# Copy any image to /tmp/fileadmin_extern/_processed_/6/d/test.jpg
# Request /processed/fileadmin/_processed_/6/d/test.w800h600m0q100.jpg
# → HTTP 400
```

## Expected behavior

Images served correctly regardless of whether `fileadmin` is a real directory or a symlink to an external storage location.

## Proposed fix

Replace the `realpath()`-based check with a normalized string comparison that resolves `..` components without following symlinks:

```php
private function normalizePath(string $path): string
{
    $parts = [];
    foreach (explode('/', $path) as $part) {
        if ($part === '..') {
            array_pop($parts);
        } elseif ($part !== '.') {
            $parts[] = $part;
        }
    }
    return implode('/', $parts);
}
```

Use `$this->normalizePath($path)` instead of `realpath($path)` in `isPathWithinPublicRoot()`. This still prevents `../`-based path traversal but does not follow symlinks.

## Workaround

Downgrade to 1.0.3 until fixed.

## Environment

- **nr-image-optimize:** 1.1.0 (works in 1.0.3)
- **TYPO3:** 12.x
- **Setup:** `fileadmin` mounted as symlink to AWS EFS via Docker named volume

### PR DESCRIPTION
**Pull request by CybotTM**
Backport of [#91](https://github.com/netresearch/t3x-nr-image-optimize/pull/91) to the \`TYPO3_12\` branch. **This is the branch line Chemnitz actually runs on** (TYPO3 v12.4.45, via \`chemnitz/cms/main\`).

See [#91](https://github.com/netresearch/t3x-nr-image-optimize/pull/91) for the full rationale — in short:

1. \`Processor::generateAndSend()\` used to return HTTP 400 silently at two points (URL pattern mismatch, path outside allowed roots). Admins had nothing in the log to diagnose against.
2. \`getAllowedRoots()\` used to cache a degraded fallback when \`StorageRepository::findAll()\` threw, poisoning the static cache for the rest of the PHP-FPM worker's life.
3. There were **zero** functional tests covering the symlinked-fileadmin scenario — all coverage was unit-only with a mocked \`StorageRepository\`.

## TYPO3_12-specific adjustments from the \`main\` PR

- **Logging uses \`error_log()\`**, not the PSR \`getLogger()\` helper: this branch keeps a narrow dependency surface and \`Processor\` does not implement \`LoggerAwareInterface\` (consistent with the existing catch-branch in \`getAllowedRoots()\`).
- **Log format**: key=value printf-style rather than PSR context array (dictated by \`error_log()\`), but the same diagnostic payload: url, pathOriginal, pathVariant, which of the two checks failed, the resolved allowedRoots list, and publicPath.

Everything else — the functional test, the cache-fix flag, the unit test for the cache-fix — is unchanged.

## Regression test

\`Tests/Functional/ProcessorSymlinkedFileadminTest.php\` reproduces the exact Chemnitz AWS ECS + EFS layout from [chemnitz/cms/main/scripts/post-deployment](https://git.netresearch.de/chemnitz/cms/main/-/blob/main/scripts/post-deployment):

\`\`\`bash
ln -sf \$efsPath/fileadmin/  /var/www/public/fileadmin
ln -sf \$efsPath/processed/  /var/www/public/processed
ln -sf \$efsPath/uploads/    /var/www/public/uploads
\`\`\`

Empirically verified (on the \`main\` PR, same test code) that the test fails when either the #70 core FAL-storage expansion OR the #76 follow-up processed/uploads expansion is removed. Not a vacuous regression test.

## Test plan

- [x] \`Build/Scripts/runTests.sh -s unit\` — **258 tests, 638 assertions, 0 errors** (incl. new \`isPathWithinAllowedRootsDoesNotCacheDegradedFallbackOnStorageThrow\`)
- [x] PHPStan, Rector (dry-run), Fractor (dry-run), CS-Fixer, Lint: all green
- [ ] Functional tests require the Imagick PHP extension which is missing on my local Docker image; CI matrix installs it explicitly (\`php-extensions: ..., imagick, gd\` in \`.github/workflows/ci.yml\`), so the 3 new tests will run there.

## Scope

Does not close #70 (already closed). Addresses the follow-up reports on v1.1.1 — Chemnitz is the known EFS-symlink reporter and will consume this as v1.1.2.

## Checklist

- [x] CI checks pass locally (except Imagick-requiring functional tests)
- [x] Tests added for each behavior change
- [ ] CHANGELOG.md — will update in the release PR
- [ ] Documentation — internal diagnostic output only, no user-facing API change

### CODE REVIEW

File: Classes/Processor.php [hunk 1]
```diff
@@ -202,15 +203,38 @@ public function generateAndSend(RequestInterface $request): ResponseInterface
...
+            error_log(sprintf(
+                'nr_image_optimize: rejecting variant request with 400 (path outside allowed roots): '
+                . 'url=%s pathOriginal=%s pathVariant=%s originalAllowed=%s variantAllowed=%s '
+                . 'allowedRoots=[%s] publicPath=%s',
+                $variantUrl,
+                $urlInfo['pathOriginal'],
+                $urlInfo['pathVariant'],
+                $originalAllowed ? '1' : '0',
+                $variantAllowed ? '1' : '0',
+                implode(', ', $this->getAllowedRoots()),
```
[the remark this answers is not in the document]
Comment (CybotTM) [reply Classes/Processor.php:258]: Addressed in [`90d8212`](https://github.com/netresearch/t3x-nr-image-optimize/pull/92/commits/90d8212) — symmetric fix to PR #91. New `$requestAllowedRoots` instance property is reset at the top of `generateAndSend()` and populated by `getAllowedRoots()` on first call, so the log-context and the two `isPathWithinAllowedRoots()` calls share one result. A `findAll()` throw now produces exactly one `error_log` line per request, not three.

File: Tests/Functional/ProcessorSymlinkedFileadminTest.php [hunk 2]
```diff
@@ -0,0 +1,286 @@
...
+     * the testing framework) with a symlink pointing at `$linkDestination`.
+     */
+    private function replaceDirWithSymlink(string $linkTarget, string $linkDestination): void
+    {
+        if (is_link($linkTarget)) {
+            unlink($linkTarget); // nosemgrep: php.lang.security.unlink-use.unlink-use -- test fixture teardown of self-created tmp symlink
+        } elseif (is_dir($linkTarget)) {
+            $this->removeRecursive($linkTarget);
+        } elseif (file_exists($linkTarget)) {
+            unlink($linkTarget); // nosemgrep: php.lang.security.unlink-use.unlink-use -- test fixture teardown of self-created tmp file
```
[the remark this answers is not in the document]
Comment (CybotTM) [reply Tests/Functional/ProcessorSymlinkedFileadminTest.php:229]: Suppressed in [`90d8212`](https://github.com/netresearch/t3x-nr-image-optimize/pull/92/commits/90d8212) with `// nosemgrep: php.lang.security.unlink-use.unlink-use` — matches the existing convention in the other test files. The path is a self-constructed temp-dir name (never user input).

File: Tests/Functional/ProcessorSymlinkedFileadminTest.php [hunk 3]
```diff
@@ -0,0 +1,286 @@
...
+    }
+
+    /**
+     * Atomically replace `$linkTarget` (likely an empty directory created by
+     * the testing framework) with a symlink pointing at `$linkDestination`.
+     */
+    private function replaceDirWithSymlink(string $linkTarget, string $linkDestination): void
+    {
+        if (is_link($linkTarget)) {
+            unlink($linkTarget); // nosemgrep: php.lang.security.unlink-use.unlink-use -- test fixture teardown of self-created tmp symlink
```
[the remark this answers is not in the document]
Comment (CybotTM) [reply Tests/Functional/ProcessorSymlinkedFileadminTest.php:225]: Suppressed in [`90d8212`](https://github.com/netresearch/t3x-nr-image-optimize/pull/92/commits/90d8212) with `// nosemgrep: php.lang.security.unlink-use.unlink-use` — matches the existing convention in the other test files. The path is a self-constructed temp-dir name (never user input).

File: Tests/Functional/ProcessorSymlinkedFileadminTest.php [hunk 4]
```diff
@@ -0,0 +1,286 @@
...
+
+    /**
+     * Recursively remove a directory tree — symlinks are unlinked without
+     * descending into their target so we don't accidentally delete the
+     * external mount contents.
+     */
+    private function removeRecursive(string $path): void
+    {
+        if (is_link($path) || is_file($path)) {
+            unlink($path); // nosemgrep: php.lang.security.unlink-use.unlink-use -- test fixture teardown of self-created tmp files
```
[the remark this answers is not in the document]
Comment (CybotTM) [reply Tests/Functional/ProcessorSymlinkedFileadminTest.php:243]: Suppressed in [`90d8212`](https://github.com/netresearch/t3x-nr-image-optimize/pull/92/commits/90d8212) with `// nosemgrep: php.lang.security.unlink-use.unlink-use` — matches the existing convention in the other test files. The path is a self-constructed temp-dir name (never user input).
